# Generated by Django 4.2.9 on 2024-01-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('calories', models.IntegerField()),
                ('protein', models.CharField(max_length=30)),
                ('fat', models.CharField(max_length=30)),
                ('carbs', models.CharField(max_length=30)),
            ],
        ),
    ]
