# Generated by Django 4.2.9 on 2024-04-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe_Instructions_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stepNumber", models.CharField(max_length=50)),
                ("step", models.CharField(max_length=255)),
                ("Name_Ingredients", models.CharField(max_length=255)),
                ("Equipment", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="carbs",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.CharField(max_length=400),
        ),
    ]
