# Generated by Django 4.2.9 on 2024-05-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_addmeal_mealdescription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="calories",
            new_name="Calories",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="fat",
            new_name="Carbs",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="protein",
            new_name="Fat",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="title",
            new_name="RecipeName",
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="image",
            new_name="recipeImage",
        ),
        migrations.AddField(
            model_name="recipe",
            name="HealthLabels",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="recipe",
            name="Protein",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
